name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy ==1.20.3
  - scipy ==1.4.0
  - matplotlib-base==3.6.0
  - pytest
  - pytest-cov
  - pytest-mpl
  - pillow==9.0.0  # needed for test compatibilty and numpy 1.20.3
